// <auto-generated />
namespace Market.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NUevos_Cambios : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NUevos_Cambios));
        
        string IMigrationMetadata.Id
        {
            get { return "201701052259303_NUevos_Cambios"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
