// <auto-generated />
namespace Market.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class New_Migration_Categoria : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(New_Migration_Categoria));
        
        string IMigrationMetadata.Id
        {
            get { return "201701050207439_New_Migration_Categoria"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
